INSERT INTO APP_USER (ID,USERNAME) values (1, 'admin');
INSERT INTO APP_USER (ID,USERNAME) values (2, 'hoangle');
INSERT INTO ITEMS (ITEM_ID,ITEM_NAME,ITEM_PRICE,ITEM_QUANTITY) values (1, 'item1',50.0,20);
INSERT INTO ITEMS (ITEM_ID,ITEM_NAME,ITEM_PRICE,ITEM_QUANTITY) values (2, 'item2',50.0,10);
